### ISSUE TITLE
Ouput of VCF2CNA

### ISSUE THREAD

**Issue by MyrtheJ** [XCLab/VCF2CNA#2]
Hello,

I successfully ran VCF2CNA on the test data. However, I don't really understand which output file contains the final copy numbers. I get a lot of files in one folder, which I presume are intermediate files (?), and within this folder also a 'result' folder. In the result folder, I got 6 files, of which 3 txt files (on of them contains the tumor purity information), 1 cnv file and two jpgs.

Could you maybe add a description of the expected results and what each file is to the READme?

Thank you!
Myrthe

**Comment by putnamdk** [comment]
Thanks for the suggestion.  We will add this.
