### ISSUE TITLE
Input file clarification

### ISSUE THREAD

**Issue by ntbeileh** [XCLab/VCF2CNA#6]
Hi,

The README states that "the types of data accepted are 1) Whole Exome Sequncing Data, 2) Paired Tumor/Normal Whole Genome Sequencing Data, 3) RNA-Seq Analysis - to determine allelic expression." If I want to run this tool on WES data to determine tumor purity do I need paired normal tissue data as well or can I just run it on tumor-only data?

Thanks!

**Comment by putnamdk** [comment]
You will need paired normal tissue data as well.
